---
- name: Resize VG
  become: true
  community.general.lvg:
    pvs: "{{ item.pvs }}"
    vg: "{{ item.name }}"
    pvresize: true
  loop: "{{ lvextend_vg }}"

- name: Extend LV size
  become: true
  community.general.lvol:
    vg: "{{ item.vgname }}"
    lv: "/dev/{{ item.vgname }}/{{ item.lvname }}"
    size: "{{ item.size }}"
    resizefs: true
    shrink: false
  loop: "{{ lvextend_lv }}"
