---
- name: Systemd daemon reload
  become: true
  ansible.builtin.systemd:
    daemon_reload: true

- name: Restart minecraft
  become: true
  ansible.builtin.systemd:
    service: minecraft.service
    state: restarted
    enabled: true
    masked: false
