---
- name: Create plugin directory
  become: true
  ansible.builtin.file:
    state: directory
    dest: "{{ bungeecord_plugins_dir }}"
    owner: "{{ bungeecord_user_uid }}"
    group: "{{ bungeecord_group_gid }}"
    mode: "0770"

- name: Check bungeecord exporter is exists
  become: true
  ansible.builtin.stat:
    path: "{{ bungeecord_exporter_jar_file_path }}"
  register: _bungeecord_exporter_jar_stat

- name: Download bungeecord exporter if not exists
  become: true
  ansible.builtin.get_url:
    url: "{{ bungeecord_exporter_download_url }}"
    dest: "{{ bungeecord_exporter_jar_file_path }}"
    owner: "{{ bungeecord_user_uid }}"
    group: "{{ bungeecord_group_gid }}"
    mode: "0640"
  when:
    - bungeecord_upgrade or
     not _bungeecord_exporter_jar_stat.stat.exists
  notify: Restart bungeecord

- name: Create bungeecord exporter dir
  become: true
  ansible.builtin.file:
    state: directory
    path: "{{ bungeecord_plugins_dir }}/BungeeCordPrometheusExporter"
    mode: "0770"
    owner: "{{ bungeecord_user_uid }}"
    group: "{{ bungeecord_group_gid }}"

- name: Copy bungeecord exporter config.yaml
  become: true
  ansible.builtin.template:
    src: exporter-config.json.j2
    dest: "{{ bungeecord_plugins_dir }}/BungeeCordPrometheusExporter/config.json"
    mode: "0640"
    owner: "{{ bungeecord_user_uid }}"
    group: "{{ bungeecord_group_gid }}"
  notify: Restart bungeecord
